var BrowserWindow = require('browser-window');
var Dialog = require('dialog');
var Fs = require('fs');
var ipc = require('ipc');
var path = require('path');

var exports = module.exports = {};

exports.exportDatapackage = function() {
  var window = BrowserWindow.getFocusedWindow();

  datapackage = new BrowserWindow({width: 450, height: 600, 'always-on-top': true});
  datapackage.loadUrl('file://' + __dirname + '/datapackage.html');

  datapackage.on('closed', function() {
    datapackage = null;
  });

  ipc.once('sendDatapackage', function(e, data, includeHeaders) {
    // data here is the object generated by filling out the form
    //debugger;
    // parse available globals to get suggested names for the data package
    var currentFileName = window.getTitle();
    var suggestedFileName = path.basename(currentFileName).replace('.csv', '');

    // issue calls to get the JSON rendering of the header row
    if(includeHeaders === "true"){
      window.webContents.send('schemaFromHeaders');
      ipc.once('jsonHeaders', function(event, json){
        //assign the headers to the JSON datapackage
        // for some reason the JSON becomes inverted at this point
        data["fields"] = json["fields"];
      });
    }
    var data = datapackageJson(data);

    Dialog.showSaveDialog({
      defaultPath: suggestedFileName+".zip",
      //defaultPath: includeHeaders,
      filters: [
        { name: 'text', extensions: ['zip'] }
      ],
      //defaultPath: 'datapackage.zip'
    }, function (fileName) {
      if (fileName === undefined) return;
      datapackage.close();
      window.webContents.send('getCSV');

      ipc.once('sendCSV', function(e, csv) {
        generateDatapackage(fileName, data, csv)
      });
    });
  });

  ipc.once('datapackageCanceled', function() {
    datapackage.close();
  });
}

function datapackageJson(data) {
  //debugger
  console.log(data);
  data.keywords = data.keywords.split(",");
  console.log(data.keywords);
  data.resources = [
    {
      "name": data.name,
      "path": "data/" + data.name + ".csv",
      "mediatype": "text/csv"
    }
  ]
  return data
}

function generateDatapackage(fileName, data, csv) {
  zip = new require('node-zip')();
  zip.file('datapackage.json', JSON.stringify(data,null, 4));
  zip.file('data/' + data.name + '.csv', csv);
  zipData = zip.generate({base64:false,compression:'DEFLATE'});
  Fs.writeFileSync(fileName, zipData, 'binary');
}
