#!/usr/bin/env bash

node ./scripts/page-build.js
electron-packager . comma-chameleon --platform=all --arch=all --version=1.0.1 --icon=resources/icon.icns --out=packages --overwrite

for Dir in $(find ./packages/* -maxdepth 0 -type d );
do
    FolderName=$(basename $Dir);
    cd ./packages/
    tar -zcf "$FolderName.tar.gz" "$FolderName"
    cd ..
done
