#!/usr/bin/env bash

# Copy `node_modules` into the app directory - this is annoying, but a side effect of the original architecture. We should probably change this
cp -r node_modules app

electron-packager app/ comma-chameleon --platform=all --arch=all --version=0.37.6 --icon=resources/icon.icns --out=packages --overwrite

for Dir in $(find ./packages/* -maxdepth 0 -type d );
do
    FolderName=$(basename $Dir);
    cd ./packages/
    tar -zcf "$FolderName.tar.gz" "$FolderName"
    cd ..
done
